#!/bin/zsh
autoload -U +X bashcompinit && bashcompinit
autoload -Uz compinit && compinit

(( $+commands[aws] )) && complete -C '/usr/local/bin/aws_completer' aws

(( $+commands[kubectl] )) && {
    source <(kubectl completion zsh)
    complete -F __start_kubectl k
}

(( $+commands[argo] )) && source <(argo completion zsh)
(( $+commands[flux] )) && source <(flux completion zsh)


# https://raw.githubusercontent.com/sbstp/kubie/master/completion/kubie.bash
(( $+commands[kubie] )) && {
    _kubiecomplete()
    {
        local cur prev

        cur=${COMP_WORDS[COMP_CWORD]}
        prev=${COMP_WORDS[COMP_CWORD-1]}

        { \unalias command; \unset -f command; } >/dev/null 2>&1 || true

        case ${COMP_CWORD} in
            1)
                cmds="ctx edit edit-config exec help info lint ns"
                COMPREPLY=($(command printf "%s\n" $cmds | command grep -e "^$cur" | command xargs))
                ;;
            2)
                case ${prev} in
                    ctx)
                        COMPREPLY=($(command kubie ctx | command grep -e "^$cur" | command xargs))
                        ;;
                    edit)
                        COMPREPLY=($(command kubie ctx | command grep -e "^$cur" | command xargs))
                        ;;
                    exec)
                        COMPREPLY=($(command kubie ctx | command grep -e "^$cur" | command xargs))
                        ;;
                    ns)
                        COMPREPLY=($(command kubie ns | command grep -e "^$cur" | command xargs))
                        ;;
                esac
                ;;
            3)
                prevprev=${COMP_WORDS[COMP_CWORD-2]}
                case ${prevprev} in
                    exec)
                        COMPREPLY=($(command kubie exec ${prev} default kubectl get namespaces|command tail -n+2|command awk '{print $1}'| command grep -e "^$cur" |command xargs))
                        ;;
                esac
                ;;
            *)
                COMPREPLY=()
                ;;
        esac
    }
    complete -F _kubiecomplete kubie
}

(( $+commands[docker] )) && source ~/.config/completion/docker.sh
(( $+commands[cetp] )) && source <(cetp completion zsh) && compdef _cetp cetp

