format = """\
  ${custom.git_profile}\
  $directory\
  $git_branch\
  $git_status\
  $git_state\
  ${custom.gcp_login}\
  ${custom.gcp}\
  $kubernetes\
  $cmd_duration\
  $line_break\
  $character"""

[directory]
style = "bold dimmed green"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol=""
format= "(| [$symbol$branch]($style) )"

[git_status]
format = "([[$all_status$ahead_behind](bold red)](bold white) )"
# prefix=""
# suffix=" "

[custom.git_profile]
command = "get-git-profile"
when="git status"
format="([\\[[$output](bold purple)\\]](bold white) )"
# prefix = "["
# suffix = "] "

[custom.gcp_login]
command = 'cat ~/.cache/gcloud/needs-login.txt'
when = "true"
format = "(| [$output](bold red) )"

[custom.gcp]
command = "echo $CLOUDSDK_CORE_PROJECT"
when='[ "\\$CLOUDSDK_CORE_PROJECT" ] && exit 0 || exit 1'
format = "(| [$output](bold yellow) )"

[kubernetes]
disabled = false
format = "[$context(\\([$namespace](bold white)\\))](bold #03a9f4) "

[cmd_duration]
style = "bold red"
min_time = 1000
format = "~ [$duration]($style) "

[character]
vicmd_symbol = "[](bold blue) "
