require("valorl.globals")
require("valorl.lsp")
require("valorl.dap")
require("valorl.compe")
require("valorl.telescope")
require("valorl.treesitter")
require("valorl.indent-blankline")
require("valorl.formatter")
