format = """\
  ${custom.git_profile}\
  $directory\
  $git_branch\
  $git_status\
  $git_state\
  ${custom.aws}\
  $kubernetes\
  $cmd_duration\
  $line_break\
  $character"""

# prompt_order = [
#   "directory",
#   "git_branch",
#   "custom.git_profile",
#   "git_status",
#   "git_state",
#   "kubernetes",
#   "aws",
#   "cmd_duration",
#   "line_break",
#   "character"
# ]

[directory]
style = "bold dimmed green"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol=""
format= "(| [$symbol$branch]($style) )"

[git_status]
format = "([[$all_status$ahead_behind](bold red)](bold white) )"
# prefix=""
# suffix=" "

[custom.git_profile]
command = "get-git-profile"
when="git status"
format="([\\[[$output](bold purple)\\]](bold white) )"
# prefix = "["
# suffix = "] "

[custom.aws]
command = '[[ "$VALORL_AWS_PROFILE_HOOK_SUSPEND" == "1" ]] && echo "$AWS_PROFILE!" || echo $AWS_PROFILE'
when='[ "\\$AWS_PROFILE" ] && exit 0 || exit 1'
format = "(| [$output](bold yellow) )"

[kubernetes]
disabled = false
format = "[$context(\\([$namespace](bold white)\\))](bold #03a9f4) "
[kubernetes.context_aliases]
"arn:aws:eks:eu-central-1:355619140320:cluster/eks_dev_sun"  = "dev(🌞)"
"arn:aws:eks:eu-central-1:355619140320:cluster/eks_dev_moon"  = "dev(🌚)"

"arn:aws:eks:eu-central-1:403980573539:cluster/eks_shrd_sun" = "shrd(🌞)"
"arn:aws:eks:eu-central-1:403980573539:cluster/eks_shrd_moon" = "shrd(🌚)"

"arn:aws:eks:eu-central-1:461308380791:cluster/eks_prod_sun" = "prod(🌞)"
"arn:aws:eks:eu-central-1:461308380791:cluster/eks_prod_moon" = "prod(🌚)"

"arn:aws:eks:eu-central-1:470547881147:cluster/eks_stag_sun" = "stag(🌞)"
"arn:aws:eks:eu-central-1:470547881147:cluster/eks_stag_moon" = "stag(🌚)"

[cmd_duration]
style = "bold red"
min_time = 1000
format = "~ [$duration]($style) "

[character]
vicmd_symbol = "[](bold blue) "
