prompt_order = [
  "directory",
  "git_branch",
  "git_status",
  "git_state",
  "custom.foo",
  "kubernetes",
  "aws",
  "cmd_duration",
  "line_break",
  "character"
]

[directory]
style = "bold dimmed green"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol=""

[git_status]
prefix=""
suffix=" "

[custom.foo]
command = "echo foo"
files = ["foo"]
when = "true"
prefix = " transcending "

[kubernetes]
disabled = false
style = "bold #03a9f4"
[kubernetes.context_aliases]
"arn:aws:eks:eu-central-1:454730462044:cluster/our_eks_cluster" = "our_eks_cluster"
"k3s-default" = "our_eks_cluster"


[aws]
symbol = " "
displayed_items = "profile"
disabled = false

[cmd_duration]
style = "bold red"
min_time = 1000
prefix = "~ "

[character]
vicmd_symbol = ""
