#!/bin/zsh

# -----------------------------------------------------------------------
# functions
function source_mdl() {
  aliasdir=$HOME/.config/aliases
  source $aliasdir/$1.zsh
}

# -----------------------------------------------------------------------

# Neovim
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -v"
alias mkd="mkdir -pv"

# Colors
alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"

# Abbreviations
alias p="sudo pacman"
alias tf="terraform"

# Utils
alias vs="find-and-open-vs-sln"
alias awp="source ~/.scripts/source-aws-profile.sh"

function repos() {
  local dir=$(find-repo)
  echo $dir
  if [ -z "$1" ]
  then
    cd $dir
  else
    setopt aliases
    $1 $dir
    unsetopt aliases
  fi
}


# Modules
source_mdl git
source_mdl kubectl

